### ISSUE TITLE
[extended_image] Disposed image called clone()

### ISSUE THREAD

**Issue by AlexV525** [openjmu/OpenJMU#216]
======== Exception caught by widgets library =======================================================
The following StateError was thrown building Positioned(left: 29.0, top: 338.3, right: 141.9, bottom: 88.6):
Bad state: Cannot clone a disposed image.
The clone() method of a previously-disposed Image was called. Once an Image object has been disposed, it can no longer be used to create handles, as the underlying data may have been released.

The relevant error-causing widget was: 
  MediaQuery file:///J:/Coding/Garages/OJGarage/OpenJMU/lib/widgets/no_scale_text_widget.dart:53:12
When the exception was thrown, this was the stack: 
#0      Image.clone (dart:ui/painting.dart:1758:7)
#1      ExtendedRawImage.createRenderObject (package:extended_image/src/image/extended_raw_image.dart:185:21)
#2      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5347:28)
...     Normal element mounting (44 frames)
#46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
...
====================================================================================================

**Comment by xmprocat** [comment]
https://github.com/xmprocat/OpenJMU/blob/master/7CB4E355112E5ECF9D3E2F5D1C2F0160.mp4

**Comment by xmprocat** [comment]
https://user-images.githubusercontent.com/38370838/110651703-a4196e00-81f6-11eb-9fe6-8b3b3631c7f0.mp4

复现步骤

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/extended_image/blob/master/lib/src/extended_image.dart#L868 The dispose method is causing the issue.
