### ISSUE TITLE
[extended_text_field] Error with 1 character handle

### ISSUE THREAD

**Issue by AlexV525** [openjmu/OpenJMU#217]
Case 1: First enter 1 character.

```shell
======== Exception caught by widgets library =======================================================
The following NoSuchMethodError was thrown building Scrollable(axisDirection: down, physics: null, restorationId: "editable", dirty, dependencies: [MediaQuery, _EffectiveTickerMode, UnmanagedRestorationScope, ScrollConfiguration], state: ScrollableState#914a3(position: ScrollPositionWithSingleContext#1ab7e(offset: 0.0, range: 0.0..0.0, viewport: 24.0, ScrollableState, ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#27a2e, ScrollDirection.idle), effective physics: ClampingScrollPhysics -> RangeMaintainingScrollPhysics)):
The method 'visitChildren' was called on null.
Receiver: null
Tried calling: visitChildren(Closure: (InlineSpan) => bool)

The relevant error-causing widget was: 
  ExtendedTextField file:///J:/Coding/Garages/OJGarage/OpenJMU/lib/pages/post/publish_post_page.dart:412:43
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      TextSpan.visitChildren (package:flutter/src/painting/text_span.dart:232:20)
#2      _Editable._extractChildren (package:extended_text_field/src/extended_editable_text.dart:2631:10)
#3      new _Editable (package:extended_text_field/src/extended_editable_text.dart:2625:21)
#4      ExtendedEditableTextState.build.<anonymous closure> (package:extended_text_field/src/extended_editable_text.dart:2433:22)
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
Null check operator used on a null value
====================================================================================================
```

Case 2: Delete the last character.

```shell
======== Exception caught by services library ======================================================
The following NoSuchMethodError was thrown during a platform message callback:
The method 'toPlainText' was called on null.
Receiver: null
Tried calling: toPlainText()

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      ExtendedEditableTextState._handleSpecialTextSpan (package:extended_text_field/src/extended_editable_text.dart:1448:41)
#2      ExtendedEditableTextState.textEditingValue= (package:extended_text_field/src/extended_editable_text.dart:2276:13)
#3      ExtendedTextSelectionRenderObject._handleDelete (package:extended_text_library/src/render_object/extended_text_selection_render_object.dart:912:28)
#4      ExtendedTextSelectionRenderObject._handleKeyEvent (package:extended_text_library/src/render_object/extended_text_selection_render_object.dart:583:7)
...
====================================================================================================
```

**Comment by xmprocat** [comment]
https://github.com/xmprocat/OpenJMU/blob/master/EE8EBB3A992DCD678EF5991FEBFC4738.mp4

**Comment by xmprocat** [comment]
https://user-images.githubusercontent.com/38370838/110651246-3a995f80-81f6-11eb-8c2d-23f9941566a5.mp4
复现步骤

**Comment by AlexV525** [comment]
More issues:

======== Exception caught by animation library =====================================================
The following _CastError was thrown while notifying listeners for AnimationController:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      ExtendedEditableTextState.renderEditable (package:extended_text_field/src/extended_editable_text.dart:2267:34)
#1      ExtendedEditableTextState._onCursorColorTick (package:extended_text_field/src/extended_editable_text.dart:2095:5)
#2      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:136:19)
#3      AnimationController.value= (package:flutter/src/animation/animation_controller.dart:366:5)
#4      ExtendedEditableTextState._stopCursorTimer (package:extended_text_field/src/extended_editable_text.dart:2167:35)
...
The AnimationController notifying listeners was: AnimationController#fd789(⏮ 0.000; paused)
====================================================================================================
