### ISSUE TITLE
Crash when clicked save button many times

### ISSUE THREAD

**Issue by xmprocat** [openjmu/OpenJMU#44]
app will clash when click more then twice on the  image save button.
多次点击图片保存按钮会引起应用崩溃

**Comment by xmprocat** [comment]
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=cn.edu.jmu.openjmu (has extras) } in com.ko2ic.imagedownloader.Downloader$execute$1@203a558
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1407)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/OpenJMU/2019-05-13.15.42.029 (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:231)
	at java.io.FileInputStream.<init>(FileInputStream.java:165)
	at com.ko2ic.imagedownloader.ImageDownloaderPlugin$CallbackImpl$granted$3.invoke(ImageDownloaderPlugin.kt:254)
	at com.ko2ic.imagedownloader.ImageDownloaderPlugin$CallbackImpl$granted$3.invoke(ImageDownloaderPlugin.kt:194)
	at com.ko2ic.imagedownloader.Downloader.resolveDownloadStatus(Downloader.kt:165)
	at com.ko2ic.imagedownloader.Downloader.access$resolveDownloadStatus(Downloader.kt:12)
	at com.ko2ic.imagedownloader.Downloader$execute$1.onReceive(Downloader.kt:31)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1397)
	... 8 more
